std: "08"
basedir: "./example"

libs:
  sim: [
    test/clock_emulator.vhdl
  ]
  common: [
    src/clock_divider.vhdl,
    src/top.vhdl,
  ]
  vga: [
    src/vga/vga_timing_gen.vhdl,
    src/vga/clock_gen.vhdl,
    src/vga/common.vhdl,
    src/vga/timing_configurations.vhdl,
  ]

tasks:
  tb_clock_divider:
    dep: [test/tb_clock_divider.vhdl, common, sim]
    arch: sim
    stop_time: 1us

  tb_clock_emulator:
    dep: [test/tb_clock_emulator.vhdl, common, sim]
    arch: sim
    stop_time: 1us

  tb_vga_clock_gen:
    dep: [test/vga/tb_vga_clock_gen.vhdl, vga, common, sim]
    arch: sim

  tb_vga_timing_gen:
    dep: [test/vga/tb_vga_timing_gen.vhdl, vga, common, sim]
    arch: sim

